# Generated by Django 3.2.25 on 2024-09-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doador',
            name='tipo_doacao',
            field=models.CharField(default='diversos', max_length=100),
        ),
        migrations.AddField(
            model_name='recebedor',
            name='necessidade',
            field=models.CharField(default='diversos', max_length=250),
        ),
    ]
