# Generated by Django 3.2.25 on 2024-09-09 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0002_auto_20240909_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_doacao', models.DateTimeField(auto_now=True)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='doacao.doador')),
                ('recebedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_recebidos', to='doacao.recebedor')),
            ],
        ),
    ]
