# Generated by Django 3.2.25 on 2024-09-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0003_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='altura',
            new_name='tamanho',
        ),
        migrations.RemoveField(
            model_name='item',
            name='comprimento',
        ),
        migrations.RemoveField(
            model_name='item',
            name='data_doacao',
        ),
        migrations.RemoveField(
            model_name='item',
            name='largura',
        ),
    ]
